### ISSUE TITLE
Template!

### ISSUE THREAD

**Issue by jchodera** [choderalab/fluorescence-assay-manuscript#1]
I have a new latex template you can use here:
https://github.com/choderalab/latex-manuscript-template

**Comment by sonyahanson** [comment]
Looks similar to the 'errors in dispensing' paper format. Are there key differences?

**Comment by jchodera** [comment]
Nope! I just cleaned up the format to use as a blank template.

**Comment by sonyahanson** [comment]
Okay cool.
